In [1]:
import numpy as np

In [2]:
a=np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
a=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
            [[5,6,7,8,9],[12,13,14,15,16],[8,5,4,6,20]]])

In [4]:
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[ 5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16],
        [ 8,  5,  4,  6, 20]]])

In [5]:
a[1,2,3]

6

In [6]:
a.shape

(2, 3, 5)

In [7]:
np.full((3,3),12.5)

array([[12.5, 12.5, 12.5],
       [12.5, 12.5, 12.5],
       [12.5, 12.5, 12.5]])

In [8]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [10]:
e=np.empty(5)

In [11]:
e

array([2.12199579e-314, 2.33647015e-307, 6.40309077e-321, 4.37131133e-312,
       5.56296645e-307])

In [12]:
data=np.random.randn(3,2)

In [13]:
data

array([[-0.54797091,  0.69818467],
       [ 0.04578873,  0.21903599],
       [-0.85034891, -1.56596252]])

In [14]:
w=np.zeros([2,3])

In [15]:
w

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
w[1,1]=11

In [17]:
w

array([[ 0.,  0.,  0.],
       [ 0., 11.,  0.]])

In [18]:
q=np.empty([2,3])
q

array([[ 0.,  0.,  0.],
       [ 0., 11.,  0.]])

In [19]:
import numpy as np

In [20]:
np.arange(3,10,4)

array([3, 7])

In [21]:
a=np.linspace(3,100,34)

In [22]:
np.random.random((3,3))

array([[0.85004167, 0.47188349, 0.27836374],
       [0.60910842, 0.38866672, 0.54016835],
       [0.66860932, 0.7915321 , 0.43306566]])

In [23]:
np.random.randint(0,10,(3,4))

array([[7, 1, 4, 6],
       [1, 0, 0, 8],
       [0, 0, 2, 7]])

In [24]:
np.random.randn(3,4)

array([[-1.81445505, -1.3086457 ,  0.26068624,  0.78221008],
       [ 0.07242152, -0.07510151,  0.79969533,  1.67485462],
       [ 0.32026024, -0.76061646,  1.08763648,  1.27745695]])

In [25]:
data=np.array('2022-12-07',dtype=np.datetime64)

In [26]:
data

array('2022-12-07', dtype='datetime64[D]')

In [27]:
def info(array):
    print(array)
    print("ndim: ", array.ndim)
    print("shape: ", array.shape)
    print("dtype: ", array.dtype)
    print("size: ", array.size)
    print("itemsize: ", array.itemsize)
    print("nbytes: ", array.nbytes)
    print("strides: ", array.strides)

In [28]:
info(a)

[  3.           5.93939394   8.87878788  11.81818182  14.75757576
  17.6969697   20.63636364  23.57575758  26.51515152  29.45454545
  32.39393939  35.33333333  38.27272727  41.21212121  44.15151515
  47.09090909  50.03030303  52.96969697  55.90909091  58.84848485
  61.78787879  64.72727273  67.66666667  70.60606061  73.54545455
  76.48484848  79.42424242  82.36363636  85.3030303   88.24242424
  91.18181818  94.12121212  97.06060606 100.        ]
ndim:  1
shape:  (34,)
dtype:  float64
size:  34
itemsize:  8
nbytes:  272
strides:  (8,)
