# Machine learning

In [1]:
# 라이브러리 사용
import pandas as pd
import tensorflow as tf

In [2]:
# 데이터 준비
# 파일들로부터 데이터 읽어오기
파일경로1 ='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레몬에이드= pd.read_csv(파일경로1)

파일경로2 ='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스톤= pd.read_csv(파일경로2)

파일경로3 ='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스= pd.read_csv(파일경로3)

In [3]:
# 데이터 모양으로 확인하기
print(레몬에이드.shape)
print(보스톤.shape)
print(아이리스.shape)

(6, 2)
(506, 14)
(150, 5)


In [4]:
# 칼럼이름 출력
print(레몬에이드.columns)
print(보스톤.columns)
print(아이리스.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [5]:
독립1=레몬에이드[['온도']]
종속1=레몬에이드[['판매량']]
print(독립1.shape,종속1.shape)

독립2=보스톤[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속2=보스톤[['medv']]
print(독립2.shape,종속2.shape)

독립3=아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속3=아이리스[['품종']]
print(독립3.shape,종속3.shape)


(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [6]:
레몬에이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [7]:
 보스톤.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [8]:
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [9]:
# 모델을 만든다.
X= tf.keras.layers.Input(shape=[1])
Y=tf.keras.layers.Dense(1)(X)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [10]:
# 모델을 학습(fit)시킨다.
model.fit(독립1,종속1,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 0s/step - loss: 153.8630
Epoch 2/100
1/1 [==============================] - 0s 14ms/step - loss: 152.0201
Epoch 3/100
1/1 [==============================] - 0s 1ms/step - loss: 150.6939
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 149.5898
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 148.6144
Epoch 6/100
1/1 [==============================] - 0s 997us/step - loss: 147.7242
Epoch 7/100
1/1 [==============================] - 0s 994us/step - loss: 146.8951
Epoch 8/100
1/1 [==============================] - 0s 998us/step - loss: 146.1122
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 145.3655
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 144.6476
Epoch 11/100
1/1 [==============================] - 0s 0s/step - loss: 143.9535
Epoch 12/100
1/1 [==============================] - 0s 0s/step - loss: 143.2793
Epoch 13/100
1/1 [===============

In [16]:
# 모델을 이용한다.
model.predict(독립1)

array([[-20.850311],
       [-21.899265],
       [-22.948221],
       [-23.997177],
       [-25.046133],
       [-26.095089]], dtype=float32)

In [17]:
model.predict([[15]])

array([[-15.605532]], dtype=float32)

# 보스턴 집 값 예측

In [18]:
보스톤.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [19]:
print(보스톤.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [20]:
독립2=보스톤[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속2=보스톤[['medv']]
print(독립2.shape,종속2.shape)

(506, 13) (506, 1)


In [14]:
X2=tf.keras.layers.Input(shape=[13])
Y2=tf.keras.layers.Dense(1)(X2)
model=tf.keras.models.Model(X2,Y2)
model.compile(loss='mse')

In [15]:
model.fit(독립2,종속2,epochs=1000, verbose=0)
model.fit(독립2,종속2,epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 1ms/step - loss: 26.1366
Epoch 2/100
16/16 [==============================] - 0s 721us/step - loss: 26.7668
Epoch 3/100
16/16 [==============================] - 0s 828us/step - loss: 26.1094
Epoch 4/100
16/16 [==============================] - 0s 735us/step - loss: 25.9721
Epoch 5/100
16/16 [==============================] - 0s 694us/step - loss: 26.1894
Epoch 6/100
16/16 [==============================] - 0s 502us/step - loss: 25.9992
Epoch 7/100
16/16 [==============================] - 0s 593us/step - loss: 26.5872
Epoch 8/100
16/16 [==============================] - 0s 679us/step - loss: 26.3445
Epoch 9/100
16/16 [==============================] - 0s 610us/step - loss: 26.2958
Epoch 10/100
16/16 [==============================] - 0s 540us/step - loss: 25.8588
Epoch 11/100
16/16 [==============================] - 0s 612us/step - loss: 26.3075
Epoch 12/100
16/16 [==============================] - 0s 634us/step - loss: 26.0526
Epo

16/16 [==============================] - 0s 672us/step - loss: 25.6501
Epoch 99/100
16/16 [==============================] - 0s 726us/step - loss: 25.7094
Epoch 100/100
16/16 [==============================] - 0s 609us/step - loss: 25.7520


In [16]:
model.predict(독립2[0:5])

array([[28.695713],
       [24.084085],
       [29.863865],
       [29.0934  ],
       [28.514435]], dtype=float32)

In [17]:
종속2[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [18]:
model.get_weights()

[array([[-0.08634288],
        [ 0.07000718],
        [-0.05075943],
        [ 3.182444  ],
        [ 1.3133097 ],
        [ 4.1891394 ],
        [ 0.01271373],
        [-0.8866026 ],
        [ 0.15338849],
        [-0.01039297],
        [-0.06018161],
        [ 0.01479646],
        [-0.5608219 ]], dtype=float32),
 array([2.8643878], dtype=float32)]

In [19]:
아이리스

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭         품종
0     5.1  3.5    1.4   0.2     setosa
1     4.9  3.0    1.4   0.2     setosa
2     4.7  3.2    1.3   0.2     setosa
3     4.6  3.1    1.5   0.2     setosa
4     5.0  3.6    1.4   0.2     setosa
..    ...  ...    ...   ...        ...
145   6.7  3.0    5.2   2.3  virginica
146   6.3  2.5    5.0   1.9  virginica
147   6.5  3.0    5.2   2.0  virginica
148   6.2  3.4    5.4   2.3  virginica
149   5.9  3.0    5.1   1.8  virginica

[150 rows x 5 columns]

In [20]:
#원핫 인코딩
인코딩=pd.get_dummies(아이리스)
인코딩

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [21]:
인코딩.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [22]:
독립3=인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속3=인코딩[['품종_setosa','품종_versicolor','품종_virginica']]
print(독립3.shape,종속3.shape)

(150, 4) (150, 3)


In [27]:
X3=tf.keras.layers.Input(shape=[4])
Y3=tf.keras.layers.Dense(3, activation='softmax')(X3)
model=tf.keras.models.Model(X3,Y3)
model.compile(loss='categorical_crossentropy',
             metrics='accuracy')

In [28]:
model.fit(독립3,종속3,epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 1.9724 - accuracy: 0.3400
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 1.8751 - accuracy: 0.3667
Epoch 3/100
5/5 [==============================] - 0s 1ms/step - loss: 1.8054 - accuracy: 0.4533
Epoch 4/100
5/5 [==============================] - 0s 908us/step - loss: 1.7461 - accuracy: 0.5400
Epoch 5/100
5/5 [==============================] - 0s 780us/step - loss: 1.6914 - accuracy: 0.5733
Epoch 6/100
5/5 [==============================] - 0s 958us/step - loss: 1.6397 - accuracy: 0.5933
Epoch 7/100
5/5 [==============================] - 0s 905us/step - loss: 1.5890 - accuracy: 0.6133
Epoch 8/100
5/5 [==============================] - 0s 888us/step - loss: 1.5392 - accuracy: 0.6133
Epoch 9/100
5/5 [==============================] - 0s 846us/step - loss: 1.4919 - accuracy: 0.6400
Epoch 10/100
5/5 [==============================] - 0s 848us/step - loss: 1.4460 - accuracy: 0.6533
Epoch 11/100
5/

5/5 [==============================] - 0s 1ms/step - loss: 0.5577 - accuracy: 0.8400
Epoch 84/100
5/5 [==============================] - 0s 797us/step - loss: 0.5559 - accuracy: 0.8467
Epoch 85/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5525 - accuracy: 0.8467
Epoch 86/100
5/5 [==============================] - 0s 1ms/step - loss: 0.5509 - accuracy: 0.8267
Epoch 87/100
5/5 [==============================] - 0s 750us/step - loss: 0.5495 - accuracy: 0.8467
Epoch 88/100
5/5 [==============================] - 0s 1ms/step - loss: 0.5467 - accuracy: 0.8467
Epoch 89/100
5/5 [==============================] - 0s 797us/step - loss: 0.5438 - accuracy: 0.8267
Epoch 90/100
5/5 [==============================] - 0s 1ms/step - loss: 0.5419 - accuracy: 0.8533
Epoch 91/100
5/5 [==============================] - 0s 844us/step - loss: 0.5395 - accuracy: 0.8600
Epoch 92/100
5/5 [==============================] - 0s 864us/step - loss: 0.5372 - accuracy: 0.8333
Epoch 93/100
5/5 [=====

In [29]:
model.predict(독립3[-5:])

array([[0.02292537, 0.24849305, 0.7285816 ],
       [0.03676362, 0.37871668, 0.5845197 ],
       [0.03599172, 0.34267047, 0.62133783],
       [0.01970177, 0.24309164, 0.73720664],
       [0.042469  , 0.39438242, 0.5631486 ]], dtype=float32)

In [30]:
종속3[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [31]:
#학습한 가중치
model.get_weights()

[array([[ 0.14506   , -0.1723266 , -0.25503832],
        [ 0.6113183 ,  0.10554768,  0.30104232],
        [-0.72266656,  0.14320463, -0.28583935],
        [-1.4155452 , -0.77165306,  0.8854191 ]], dtype=float32),
 array([ 0.17671497,  0.22020553, -0.3166622 ], dtype=float32)]

# 히든레이어, 여러개의 뉴런

In [32]:
print(독립2.shape,독립2.shape)

(506, 13) (506, 13)


In [33]:
X2=tf.keras.layers.Input(shape=[13])
H2=tf.keras.layers.Dense(10, activation='swish')(X2)
Y2=tf.keras.layers.Dense(1)(H2)
model=tf.keras.models.Model(X2,Y2)
model.compile(loss='mse')

In [34]:
model.summary()

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_7 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(독립2,종속2,epochs=1000,verbose=0)
model.fit(독립2,종속2,epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 991us/step - loss: 21.3188
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 22.2906
Epoch 3/10
16/16 [==============================] - 0s 980us/step - loss: 22.4832
Epoch 4/10
16/16 [==============================] - 0s 630us/step - loss: 21.0146
Epoch 5/10
16/16 [==============================] - 0s 614us/step - loss: 20.9114
Epoch 6/10
16/16 [==============================] - 0s 759us/step - loss: 23.2691
Epoch 7/10
16/16 [==============================] - 0s 740us/step - loss: 21.3586
Epoch 8/10
16/16 [==============================] - 0s 718us/step - loss: 21.9782
Epoch 9/10
16/16 [==============================] - 0s 796us/step - loss: 21.2924
Epoch 10/10
16/16 [==============================] - 0s 743us/step - loss: 22.7166


In [36]:
print(model.predict(독립2[:5]))
print(종속2[:5])

[[28.45493 ]
 [23.405205]
 [29.451294]
 [28.738148]
 [28.280611]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [37]:
X3=tf.keras.layers.Input(shape=[4])
H3=tf.keras.layers.Dense(8, activation='swish')(X3)
H3=tf.keras.layers.Dense(8, activation='swish')(H3)
H3=tf.keras.layers.Dense(8, activation='swish')(H3)
Y3=tf.keras.layers.Dense(3, activation='softmax')(H3)
model=tf.keras.models.Model(X3,Y3)
model.compile(loss='categorical_crossentropy',
             metrics='accuracy')

In [38]:
model.fit(독립3,종속3,epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 4ms/step - loss: 3.0471 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 2.2835 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 1ms/step - loss: 1.8302 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 1ms/step - loss: 1.5043 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 1ms/step - loss: 1.2767 - accuracy: 0.3333
Epoch 6/100
5/5 [==============================] - 0s 945us/step - loss: 1.1269 - accuracy: 0.3533
Epoch 7/100
5/5 [==============================] - 0s 1ms/step - loss: 1.0372 - accuracy: 0.6400
Epoch 8/100
5/5 [==============================] - 0s 1ms/step - loss: 0.9781 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 1ms/step - loss: 0.9449 - accuracy: 0.6667
Epoch 10/100
5/5 [==============================] - 0s 1ms/step - loss: 0.9216 - accuracy: 0.6533
Epoch 11/100
5/5 [=========

Epoch 84/100
5/5 [==============================] - 0s 893us/step - loss: 0.1312 - accuracy: 0.9800
Epoch 85/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1348 - accuracy: 0.9667
Epoch 86/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1275 - accuracy: 0.9733
Epoch 87/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1215 - accuracy: 0.9733
Epoch 88/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1206 - accuracy: 0.9733
Epoch 89/100
5/5 [==============================] - 0s 955us/step - loss: 0.1233 - accuracy: 0.9667
Epoch 90/100
5/5 [==============================] - 0s 798us/step - loss: 0.1175 - accuracy: 0.9800
Epoch 91/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1191 - accuracy: 0.9800
Epoch 92/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1199 - accuracy: 0.9733
Epoch 93/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1114 - accuracy: 0.9667
Epoch 94/100
5

In [39]:
print(model.predict(독립3[0:5]))

[[9.9611795e-01 3.8817921e-03 1.9268846e-07]
 [9.9097520e-01 9.0239039e-03 9.6512917e-07]
 [9.9405378e-01 5.9456183e-03 5.9170969e-07]
 [9.9052423e-01 9.4745615e-03 1.2257403e-06]
 [9.9652714e-01 3.4727703e-03 1.7030251e-07]]


In [40]:
print(종속3[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [41]:
print(아이리스.dtypes)

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종        object
dtype: object


In [42]:
아이리스.isna().sum()

꽃잎길이     0
꽃잎폭      0
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64

In [43]:
아이리스.tail()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭         품종
145   6.7  3.0    5.2   2.3  virginica
146   6.3  2.5    5.0   1.9  virginica
147   6.5  3.0    5.2   2.0  virginica
148   6.2  3.4    5.4   2.3  virginica
149   5.9  3.0    5.1   1.8  virginica