# 1. 과거의 데이터를 준비
# 2. 모델의 구조를 만든다
# 3. 데이터로 모델을 학습(Fit)
# 4. 모델을 이용

# 데이터 준비하기1
### 실습을 통해 배울 도구들
        파일 읽어오기
        모양 확인하기
        칼럼 선택하기
        칼럼 이름 출력하기
        맨 위 5개 관측치 출력하기

In [2]:
import pandas as pd

In [3]:
# 파일들로부터 데이터 읽어오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레몬에이드 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스톤 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [4]:
# 데이터 모양으로 확인하기
print(레몬에이드.shape)
print(보스톤.shape)
print(아이리스.shape)

(6, 2)
(506, 14)
(150, 5)


In [5]:
# 칼럼이름 출력
print(레몬에이드.columns)
print(보스톤.columns)
print(아이리스.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [6]:
독립 = 레몬에이드 [['온도']]
종속 = 레몬에이드 [['판매량']]
print(독립.shape, 종속.shape)

독립 = 보스톤 [['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스톤 [['medv']]
print(독립.shape, 종속.shape)

독립 = 아이리스 [['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스 [['품종']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [7]:
레몬에이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [8]:
보스톤.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [9]:
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [10]:
# 7강 들으면 됨

In [11]:
# 1. 과거의 데이터를 준비
독립 = 레몬에이드 [['온도']]
종속 = 레몬에이드 [['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [30]:
독립 = 보스톤 [['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스톤 [['medv']]
print(독립.shape, 종속.shape)

독립 = 아이리스 [['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스 [['품종']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)
(150, 4) (150, 1)


In [31]:
import tensorflow as tf

In [32]:
# 2. 모델의 구조를 만든다.
x=tf.keras.layers.Input(shape=[1])
y=tf.keras.layers.Dense(1)(x)
model=tf.keras.models.Model(x,y)
model.compile(loss='mse')

In [33]:
# 3. 데이터로 모델을 학습(FIT)
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000


ValueError: in user code:

    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\functional.py:385 call
        return self._run_internal_graph(
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\functional.py:508 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:212 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer dense_4 is incompatible with the layer: expected axis -1 of input shape to have value 1 but received input with shape [None, 4]


In [34]:
print("Predictions: ",model.predict([[80]]))

Predictions:  [[-101.59859]]


In [27]:
# 8강

In [26]:
model.fit(독립, 종속, epochs=1000)
#Epoch는 전체 몇번을 했는지/ 학습의 시간은 얼마나 걸렸는지/ loss는 (예측-결과)^2
#Loss가 0과 가까울수록 정확한거임

Epoch 1/1000


ValueError: in user code:

    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\functional.py:385 call
        return self._run_internal_graph(
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\functional.py:508 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\coding\.conda\envs\DHML\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:212 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer dense_2 is incompatible with the layer: expected axis -1 of input shape to have value 1 but received input with shape [None, 4]


In [37]:
print("Predictions: ",model.predict([[80]]))
#다음 Prediction으로 결과를 예측해볼 때 loss가 0과 가깝게 나올수록 예측이 정확함

Predictions:  [[159.93292]]


In [38]:
#9강

In [35]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [36]:
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
데이터.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [37]:
# 종속변수, 독립변수
독립=데이터[['온도']] # 원인값
종속=데이터[['판매량']] # 결과값
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [38]:
# 모델을 만든다.
x=tf.keras.layers.Input(shape=[1])
y=tf.keras.layers.Dense(1)(x)
model=tf.keras.models.Model(x,y)
model.compile(loss='mse')

In [40]:
# 모델을 합습시킵니다.
model.fit(독립, 종속, epochs=1000, verbose=10) #verbose=0이면 출력 안나오게 함

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

Epoch 592/1000
Epoch 593/1000
Epoch 594/1000
Epoch 595/1000
Epoch 596/1000
Epoch 597/1000
Epoch 598/1000
Epoch 599/1000
Epoch 600/1000
Epoch 601/1000
Epoch 602/1000
Epoch 603/1000
Epoch 604/1000
Epoch 605/1000
Epoch 606/1000
Epoch 607/1000
Epoch 608/1000
Epoch 609/1000
Epoch 610/1000
Epoch 611/1000
Epoch 612/1000
Epoch 613/1000
Epoch 614/1000
Epoch 615/1000
Epoch 616/1000
Epoch 617/1000
Epoch 618/1000
Epoch 619/1000
Epoch 620/1000
Epoch 621/1000
Epoch 622/1000
Epoch 623/1000
Epoch 624/1000
Epoch 625/1000
Epoch 626/1000
Epoch 627/1000
Epoch 628/1000
Epoch 629/1000
Epoch 630/1000
Epoch 631/1000
Epoch 632/1000
Epoch 633/1000
Epoch 634/1000
Epoch 635/1000
Epoch 636/1000
Epoch 637/1000
Epoch 638/1000
Epoch 639/1000
Epoch 640/1000
Epoch 641/1000
Epoch 642/1000
Epoch 643/1000
Epoch 644/1000
Epoch 645/1000
Epoch 646/1000
Epoch 647/1000
Epoch 648/1000
Epoch 649/1000
Epoch 650/1000
Epoch 651/1000
Epoch 652/1000
Epoch 653/1000
Epoch 654/1000
Epoch 655/1000
Epoch 656/1000
Epoch 657/1000
Epoch 658/

In [41]:
# 모델을 이용한다.
model.predict(독립)

array([[19.33082 ],
       [20.197393],
       [21.063969],
       [21.930544],
       [22.797117],
       [23.66369 ]], dtype=float32)

In [53]:
종속

판매량
0   40
1   42
2   44
3   46
4   48
5   50

In [55]:
model.predict([[15]]) #15도 일때 몇개의 레몬에이드를 준비해야하는지

array([[30.178846]], dtype=float32)

In [56]:
# 10강

In [79]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스톤 = pd.read_csv(파일경로)

In [42]:
# 1.과거의 데이터를 준비
독립 = 보스톤 [['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스톤 [['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [43]:
# 2.모델의 구조를 만듬
x=tf.keras.layers.Input(shape=[13])
y=tf.keras.layers.Dense(1)(x)
model=tf.keras.models.Model(x,y)
model.compile(loss='mse')

In [44]:
# 3.데이터로 모델을 학습(Fit)
model.fit(독립,종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 2ms/step - loss: 79533.5391
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 70443.5391
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 63061.5781
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 56281.5117
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 49956.6484
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 44017.9648
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 38451.8555
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 33372.0547
Epoch 9/100
16/16 [==============================] - 0s 1ms/step - loss: 28732.9922
Epoch 10/100
16/16 [==============================] - 0s 3ms/step - loss: 24492.8047
Epoch 11/100
16/16 [==============================] - 0s 2ms/step - loss: 20646.6816
Epoch 12/100
16/16 [==============================] - 0s 2ms/step - loss: 

16/16 [==============================] - 0s 3ms/step - loss: 59.2788
Epoch 100/100
16/16 [==============================] - 0s 2ms/step - loss: 58.7234


In [45]:
print("Predictions: ", model.predict(독립[0:5]))

Predictions:  [[32.159863]
 [24.771263]
 [25.597715]
 [25.097048]
 [25.160643]]


In [88]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [72]:
보스톤

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [76]:
#종속 2개일때
x=tf.keras.layers.Input(shape=[12])
y=tf.keras.layers.Dense(2)(x)
model=tf.keras.models.Model(x,y)
model.compile(loss='mse')

In [91]:
model.get_weights()

[array([[-0.0928362 ],
        [ 0.04753739],
        [-0.02228101],
        [ 2.6505284 ],
        [-1.9830197 ],
        [ 5.245866  ],
        [-0.01045247],
        [-1.0670012 ],
        [ 0.19889927],
        [-0.01098691],
        [-0.51880187],
        [ 0.01279402],
        [-0.46354702]], dtype=float32),
 array([8.492062], dtype=float32)]

In [92]:
#14강 아이리스 분류 예측

In [56]:
import pandas as pd
import tensorflow as tf

In [33]:
# 아이리스는 범주형 데이터임
# 종속변수가 양적데이터이면 -> 회귀(regression)
# 종속변수가 범주형데이터이면 -> 분류 classification

In [57]:
# 1. 과거의 데이터를 가져온다
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
인코딩 = pd.get_dummies(아이리스)
#onehot-encoding
#아이리스 = pd.get_dummies(아이리스)
#모든 범주형데이터를 원핫인코딩시킴
#데이터가 0 또는 1로 만드는 과정임

In [58]:
인코딩

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [59]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [67]:
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]

In [68]:
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [71]:
# 2. 모델의 구조를 만든다.
x=tf.keras.layers.Input(shape=[4])
y=tf.keras.layers.Dense(3, activation='softmax')(x)
model=tf.keras.models.Model(x,y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')
#softmax
#categorical_crossentropy
#여기서의 loss는 crossentropy로 사용//문제에 따라 loss를 다르게 선택해야 함.

In [72]:
# 분류 예측 = 정답을 확률표현으로
# 내일 비가 올 확률이 30%
# 합불 99%
# 동전 앞면 50%
# 0%~100% 로 예측하는거 = Sigmoid , Softmax

In [77]:
# 3. 데이터로 모델을 학습(fit)시킨다
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.8139 - accuracy: 0.4000
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.7823 - accuracy: 0.3867
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.7496 - accuracy: 0.3867
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.7166 - accuracy: 0.3800
Epoch 5/1000
5/5 [==============================] - 0s 1ms/step - loss: 1.6862 - accuracy: 0.3800
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.6537 - accuracy: 0.3800
Epoch 7/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.6232 - accuracy: 0.4067
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.5919 - accuracy: 0.3800
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.5595 - accuracy: 0.3867
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.5261 - accuracy: 0.4067
Epoch 11/1000
5/5 [

5/5 [==============================] - 0s 139us/step - loss: 0.4552 - accuracy: 0.9267
Epoch 166/1000
5/5 [==============================] - 0s 0s/step - loss: 0.4543 - accuracy: 0.9267
Epoch 167/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.4528 - accuracy: 0.9067
Epoch 168/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.4525 - accuracy: 0.9267
Epoch 169/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.4503 - accuracy: 0.9200
Epoch 170/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.4496 - accuracy: 0.9200
Epoch 171/1000
5/5 [==============================] - 0s 171us/step - loss: 0.4488 - accuracy: 0.9267
Epoch 172/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.4477 - accuracy: 0.9267
Epoch 173/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.4462 - accuracy: 0.9200
Epoch 174/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.4464 - accuracy: 0.9133
Epoch 175/10

5/5 [==============================] - 0s 2ms/step - loss: 0.3824 - accuracy: 0.9467
Epoch 248/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.3816 - accuracy: 0.9533
Epoch 249/1000
5/5 [==============================] - 0s 0s/step - loss: 0.3811 - accuracy: 0.9600
Epoch 250/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.3800 - accuracy: 0.9600
Epoch 251/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.3793 - accuracy: 0.9533
Epoch 252/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.3791 - accuracy: 0.9533
Epoch 253/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.3787 - accuracy: 0.9400
Epoch 254/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.3777 - accuracy: 0.9533
Epoch 255/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.3767 - accuracy: 0.9533
Epoch 256/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.3758 - accuracy: 0.9600
Epoch 257/1000
5

5/5 [==============================] - 0s 0s/step - loss: 0.2886 - accuracy: 0.9733
Epoch 412/1000
5/5 [==============================] - 0s 0s/step - loss: 0.2880 - accuracy: 0.9733
Epoch 413/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2877 - accuracy: 0.9800
Epoch 414/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2875 - accuracy: 0.9800
Epoch 415/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2869 - accuracy: 0.9667
Epoch 416/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2865 - accuracy: 0.9667
Epoch 417/1000
5/5 [==============================] - 0s 0s/step - loss: 0.2857 - accuracy: 0.9733
Epoch 418/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2856 - accuracy: 0.9733
Epoch 419/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2849 - accuracy: 0.9733
Epoch 420/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2845 - accuracy: 0.9733
Epoch 421/1000
5/5

5/5 [==============================] - 0s 2ms/step - loss: 0.2289 - accuracy: 0.9733
Epoch 576/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.2287 - accuracy: 0.9733
Epoch 577/1000
5/5 [==============================] - 0s 744us/step - loss: 0.2280 - accuracy: 0.9733
Epoch 578/1000
5/5 [==============================] - 0s 305us/step - loss: 0.2285 - accuracy: 0.9733
Epoch 579/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2275 - accuracy: 0.9733
Epoch 580/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2274 - accuracy: 0.9733
Epoch 581/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.2277 - accuracy: 0.9733
Epoch 582/1000
5/5 [==============================] - 0s 0s/step - loss: 0.2268 - accuracy: 0.9733
Epoch 583/1000
5/5 [==============================] - 0s 0s/step - loss: 0.2263 - accuracy: 0.9733
Epoch 584/1000
5/5 [==============================] - 0s 0s/step - loss: 0.2262 - accuracy: 0.9733
Epoch 585/1000

5/5 [==============================] - 0s 2ms/step - loss: 0.1903 - accuracy: 0.9667
Epoch 739/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1897 - accuracy: 0.9667
Epoch 740/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1905 - accuracy: 0.9733
Epoch 741/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.1892 - accuracy: 0.9667
Epoch 742/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1889 - accuracy: 0.9667
Epoch 743/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1893 - accuracy: 0.9733
Epoch 744/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1889 - accuracy: 0.9667
Epoch 745/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1886 - accuracy: 0.9667
Epoch 746/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1882 - accuracy: 0.9667
Epoch 747/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1882 - accuracy: 0.9667
Epoch 748/1000


5/5 [==============================] - 0s 2ms/step - loss: 0.1757 - accuracy: 0.9667
Epoch 821/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1753 - accuracy: 0.9667
Epoch 822/1000
5/5 [==============================] - 0s 0s/step - loss: 0.1750 - accuracy: 0.9733
Epoch 823/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.1747 - accuracy: 0.9667
Epoch 824/1000
5/5 [==============================] - 0s 0s/step - loss: 0.1761 - accuracy: 0.9667
Epoch 825/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1749 - accuracy: 0.9667
Epoch 826/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1745 - accuracy: 0.9733
Epoch 827/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1743 - accuracy: 0.9667
Epoch 828/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1743 - accuracy: 0.9667
Epoch 829/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1738 - accuracy: 0.9733
Epoch 830/1000
5/

5/5 [==============================] - 0s 2ms/step - loss: 0.1535 - accuracy: 0.9667
Epoch 983/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9667
Epoch 984/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1529 - accuracy: 0.9667
Epoch 985/1000
5/5 [==============================] - 0s 434us/step - loss: 0.1536 - accuracy: 0.9667
Epoch 986/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1525 - accuracy: 0.9667
Epoch 987/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1524 - accuracy: 0.9667
Epoch 988/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1526 - accuracy: 0.9667
Epoch 989/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1527 - accuracy: 0.9667
Epoch 990/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9667
Epoch 991/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1520 - accuracy: 0.9667
Epoch 992/100

In [80]:
# 4. 모델의 이용
model.predict(독립[-5:])

array([[6.0823101e-07, 9.8041900e-02, 9.0195751e-01],
       [9.7547968e-07, 1.4688556e-01, 8.5311341e-01],
       [2.7368453e-06, 2.1826114e-01, 7.8173614e-01],
       [1.1902639e-06, 1.1134950e-01, 8.8864934e-01],
       [8.2627002e-06, 2.9925051e-01, 7.0074129e-01]], dtype=float32)

In [81]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [83]:
#학습한 가중치
model.get_weights()

[array([[ 0.84592414,  0.8157421 ,  0.08752472],
        [ 3.1498756 ,  0.0803937 , -1.8647603 ],
        [-3.2484317 ,  0.09458306,  1.4536297 ],
        [-3.6280508 , -1.2622296 ,  2.3677385 ]], dtype=float32),
 array([ 2.2063944 ,  0.78234684, -1.6999319 ], dtype=float32)]

In [84]:
# 18강. hidden layer

In [88]:
# 지금까지는 뉴런 1개 hiddenlayer 사용해서 진짜 딥 러닝을 만들어볼거임
# Input layer -> hidden layer -> Ouput layer

In [89]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스톤 = pd.read_csv(파일경로)

In [92]:
독립 = 보스톤 [['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스톤 [['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [94]:
x=tf.keras.layers.Input(shape=[13])
h=tf.keras.layers.Dense(10, activation='swish')(x)
b=tf.keras.layers.Dense(1)(h)
model=tf.keras.models.Model(x,y)
model.compile(loss='mse')

In [98]:
model.summary()

Model: "functional_33"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_17 (InputLayer)        [(None, 13)]              0         
_________________________________________________________________
dense_26 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_27 (Dense)             (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [97]:
model.fit(독립,종속,epochs=1000, verbose=0)
model.fit(독립,종속,epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 12.9321
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 12.3334
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 12.4994
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 11.8580
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 13.7315
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 12.6400
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 12.7918
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 13.4184
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1000
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 14.4752


In [99]:
print(model.predict(독립[:5]))
print(종속[:5])

[[26.972136]
 [23.56978 ]
 [29.024775]
 [30.1449  ]
 [29.33101 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [100]:
# 아이리스도 해봄

In [101]:
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [104]:
# 2. 모델의 구조를 만든다.
x=tf.keras.layers.Input(shape=[4])
h=tf.keras.layers.Dense(8, activation='swish')(x)
h=tf.keras.layers.Dense(8, activation='swish')(h)
h=tf.keras.layers.Dense(8, activation='swish')(h)
y=tf.keras.layers.Dense(3, activation='softmax')(h)
model=tf.keras.models.Model(x,y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')
#softmax
#categorical_crossentropy
#여기서의 loss는 crossentropy로 사용//문제에 따라 loss를 다르게 선택해야 함.

In [105]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0518 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0441 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0515 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0445 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 0s/step - loss: 0.0471 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 0s/step - loss: 0.0450 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0465 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0503 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 0s/step - loss: 0.0521 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 0s/step - loss: 0.0460 - accuracy: 0.9800


In [107]:
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9999881e-01 1.1612030e-06 1.9059532e-11]
 [9.9999797e-01 2.0050861e-06 4.6009214e-11]
 [9.9999833e-01 1.6482796e-06 4.2061375e-11]
 [9.9999833e-01 1.7074692e-06 4.3125243e-11]
 [9.9999869e-01 1.3139531e-06 2.1028599e-11]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


# ㅡㅡㅡㅡㅡㅡㅡ딥러닝실습은 끝ㅡㅡㅡㅡㅡㅡㅡㅡ

In [109]:
# 20강부터