In [1]:
import numpy as np

# Numpy 기본

In [16]:
a1=np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5


In [22]:
a2=np.array([ [1,2,3,4], [4,5,6,9], [7,8,9,2] ])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3 4]
 [4 5 6 9]
 [7 8 9 2]]
(3, 4)
1 5 9


In [29]:
a3=np.array([ [ [1,2,3],[4,5,6],[7,8,9] ],
              [ [1,2,3],[4,5,6],[7,8,9] ],
              [ [1,2,3],[4,5,6],[7,8,9] ] ])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


# 배열 생성 및 초기화

In [31]:
np.zeros(10)
# 10개의 요소를 0으로

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(10)
#위랑 같은 원리

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones((3,3))
#개수를 의미할때는 소괄호

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [39]:
np.eye(5)
# 단위행렬(identity matrix)생성
# 주 대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.tri(3)
# 삼각행렬 생성

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [43]:
np.empty(10)
# 초기화되지 않은 배열을 생성
# 초기화가 없어서 배열 생성비용 저렴하고 빠름
# 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
# _like(): 지전된 배열과 shape가 같은 행렬 생성
print(a2)
print(np.zeros_like(a2))
print(np.ones_like(a2))
print(np.full_like(a2,10))

[[1 2 3 4]
 [4 5 6 9]
 [7 8 9 2]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


# 생성한 값으로 배열 생성

In [55]:
np.arange(0,30,2)
#range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [57]:
np.linspace(0,1,5)
# 0부터 1인데 5개로 균등하게 만들어줘

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [59]:
np.logspace(0.1, 1, 20)
# 0.1부터 1까지 균등하게 20개를 logsclae로 배열생성

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

# 랜덤값으로 배열 생성

In [62]:
np.random.random((3,4))
# 3by4로 랜덤하게 만들때

array([[0.33843164, 0.4947684 , 0.39187914, 0.59126938],
       [0.19071186, 0.22862309, 0.60074866, 0.83376166],
       [0.2175582 , 0.45621776, 0.52399996, 0.97434899]])

In [65]:
np.random.randint(0,10,(3,4))
# 0부터 10까지 3by4로 랜덤하게 int로 만들때

array([[7, 5, 6, 6],
       [4, 0, 1, 0],
       [1, 9, 2, 7]])

In [67]:
np.random.normal(0, 1, (3,4))
# 정규분포를 고려해 랜덤한 수의 배열을 생성
# 평균=0, 표준편차=1, 3by4 배열

array([[-0.10263209,  1.3258792 , -0.43732228,  0.14650653],
       [ 1.26017723,  0.50681686, -1.20022979, -0.69776831],
       [-0.22033064,  0.35926188, -0.66312982,  1.13846209]])

In [70]:
np.random.rand(3,4)
# 균등분포(uniform distribution)을 고려해 랜덤한 수의 배열을 생성

array([[0.21487754, 0.52711174, 0.52516891, 0.97162903],
       [0.87027724, 0.71806707, 0.18899064, 0.15115009],
       [0.96450602, 0.20281783, 0.77986703, 0.22967356]])

In [71]:
np.random.randn(3,4)
# 표준 정규 분포(standard normal distribution)를 고려해 랜덤한 수의 배열 생성

array([[ 1.21692459, -1.6845702 ,  0.53692959,  0.28874462],
       [-0.07984104,  1.08863022, -0.39426561, -0.39831928],
       [ 1.69489665, -0.63948107,  1.08144524,  0.43414065]])

# 표준 데이터 타입

In [72]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
np.tri(5,dtype=bool)

array([[ True, False, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [79]:
np.full((3,4), 1.0 , dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 날짜/시간 배열 생성

In [85]:
data= np.array('2020-01-01',dtype=np.datetime64)
data

array('2020-01-01', dtype='datetime64[D]')

In [86]:
data+np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [88]:
datetime=np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [91]:
datetime=np.datetime64('2020-06-01 12:00:15.344345','ns')
datetime

numpy.datetime64('2020-06-01T12:00:15.344345000')

# 배열 조회

## 배열 속성 정보

In [96]:
def a_info(array):
    print(array)
    print("ndim: ", array.ndim) #축의 갯수
    print("shape: ", array.shape) #축의 크기
    print("dtype: ", array.dtype) #요소의 타입
    print("size: ", array.size) #전체 갯수
    print("itemsize: ", array.itemsize) #타입의 byte크기
    print("nbytes: ", array.nbytes) #차지하는 byte수
    print("strides: ", array.strides)

In [98]:
a_info(a1)

[1 2 3 4 5]
ndim:  1
shape:  (5,)
dtype:  int32
size:  5
itemsize:  4
nbytes:  20
strides:  (4,)


In [99]:
a_info(a2)

[[1 2 3 4]
 [4 5 6 9]
 [7 8 9 2]]
ndim:  2
shape:  (3, 4)
dtype:  int32
size:  12
itemsize:  4
nbytes:  48
strides:  (16, 4)


In [100]:
a_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim:  3
shape:  (3, 3, 3)
dtype:  int32
size:  27
itemsize:  4
nbytes:  108
strides:  (36, 12, 4)


## Indexing

In [103]:
print(a1)
print(a1[0])
print(a1[-1])
print(a1[-2])

[1 2 3 4 5]
1
5
4


In [104]:
print(a2)
print(a2[0,0])
print(a2[-1,2])
print(a2[-2,1])

[[1 2 3 4]
 [4 5 6 9]
 [7 8 9 2]]
1
9
5


In [105]:
print(a3)
print(a3[0,0,0])
print(a3[-1,2,1])
print(a3[-2,1,1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
8
5


## Slicing

In [107]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1]
[1 3 5]
[5 4 3 2 1]


In [109]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2,:2])
print(a2[1:, ::-1])
print(a2[::-1 ,::-1])

[[1 2 3 4]
 [4 5 6 9]
 [7 8 9 2]]
[4 5 6 9]
[4 5 6 9]
[[1 2]
 [4 5]]
[[9 6 5 4]
 [2 9 8 7]]
[[2 9 8 7]
 [9 6 5 4]
 [4 3 2 1]]


## Boolean Indexing

In [111]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
# 배열을 True, False로 지정
# True 값인 인덱스 값만 조회

[1 2 3 4 5]
[2 3 5]


In [130]:
print(a2)
bi=np.random.randint(0, 2, (3,4), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3 4]
 [4 5 6 9]
 [7 8 9 2]]
[[ True False False  True]
 [False False False  True]
 [ True False False False]]
[1 4 9 7]


## 팬시 인덱싱(Fancy Indexing)

In [136]:
print(a1)
print([a1[0],a1[2]])
ind=[0,2]
print(a1[ind])
ind=np.array([[0,1],
            [2,0]])
print(a1[ind])

[1 2 3 4 5]
[1, 3]
[1 3]
[[1 2]
 [3 1]]


In [139]:
print(a2)
row=np.array([0,2])
col=np.array([1,2])
print(a2[row,col])
print(a2[row,:])
print(a2[:,col])
print(a2[row,1])
print(a2[2,col])
print(a2[row,1:])
print(a2[1:,col])

[[1 2 3 4]
 [4 5 6 9]
 [7 8 9 2]]
[2 9]
[[1 2 3 4]
 [7 8 9 2]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3 4]
 [8 9 2]]
[[5 6]
 [8 9]]


# 배열 값 삽입/수정/삭제/복사

## 배열 값 삽입

In [142]:
https://www.youtube.com/watch?v=mirZPrWwvao
    46:30 / 2:25:00

SyntaxError: invalid syntax (<ipython-input-142-d1a04325c114>, line 1)