In [1]:
import numpy as np

In [2]:
list_data=[1,2,3]
array=np.array(list_data)

In [3]:
print(array.size)

3


In [4]:
print(array.dtype)

int32


In [5]:
array[2]

3

In [6]:
array1= np.arange(4)

In [7]:
array1

array([0, 1, 2, 3])

# 

In [8]:
array2=np.zeros((4,4),dtype=float)

In [14]:
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 

In [17]:
array3=np.ones((3,3),dtype=float)

In [18]:
array3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 

In [23]:
array4=np.random.randint(0,10, (3,3))

In [24]:
array4

array([[8, 0, 5],
       [0, 0, 0],
       [7, 4, 4]])

# 

In [27]:
array5=np.random.normal(0,1,(3,3))

In [28]:
array5

array([[-0.41080612,  0.3173604 , -0.67638185],
       [ 0.35628794, -0.68204963, -1.96118693],
       [-0.20224283,  0.44062278,  1.55475826]])

# 

In [29]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.concatenate([a1,a2])

In [30]:
a3

array([1, 2, 3, 4, 5, 6])

# 

In [34]:
b1=np.array([1,2,3,4])
b2=b1.reshape((2,2))

In [35]:
b2

array([[1, 2],
       [3, 4]])

# 

In [49]:
c1=np.arange(4).reshape(1,4)
c2=np.arange(8).reshape(2,4)
c3=np.concatenate([c1,c2],axis=0) 
c4=c3.reshape(6,2)

In [50]:
c3

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
c4

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

# 

In [51]:
d1=np.arange(8).reshape(2,4)

In [52]:
d1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
left, right=np.split(d1, [2], axis=1)

In [69]:
left

array([[0, 1],
       [4, 5]])

In [70]:
right

array([[2, 3],
       [6, 7]])